/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/jocelynrosario/Downloads/3d-portfolio-main/public/models/game.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Computer(props) {
  const { nodes, materials } = useGLTF('models/game.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.373}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Screen_Low_body_0.geometry} material={materials['body.001']} />
            <mesh geometry={nodes.Screen_Low_body_0001.geometry} material={materials.Material} />
            <mesh geometry={nodes.Screen_Low_glass_0.geometry} material={materials['glass.001']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/game.glb')

export default Computer;
