/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 LennysOffice.glb 
*/

import React, { useMemo } from "react";
import { useGLTF } from "@react-three/drei";
import { convertMaterialsToBasic } from "../convertToBasic";

export default function Room(props) {
  const { nodes, materials } = useGLTF("models/LennysOffice.glb");
  useMemo(() => convertMaterialsToBasic(materials), [materials]);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Bed_Baked.geometry}
        material={materials.Fifth_Bed_Baked}
        position={[1.231, 0.358, 1.2]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Fourth_Baked.geometry}
        material={materials.Fourth_Actual_Baked}
        position={[2.455, 2.209, 0.272]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Room_Baked.geometry}
        material={materials.Room_First_Baked}
      />
      <mesh
        geometry={nodes.Desk_Baked.geometry}
        material={materials.Desk_Second_FINAL_Baked}
        position={[0.084, 0.362, -1.257]}
      />
      <mesh
        geometry={nodes.Extras_Baked.geometry}
        material={materials.Extras_Third_Baked}
        position={[2.07, 0.025, 0.102]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={1.212}
      />
    </group>
  );
}

useGLTF.preload("models/LennysOffice.glb");
